version: '3.9'

services:
  mongodb:
    image: mongo
    container_name: my-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  app:
    build: .
    container_name: singularis-test-task
    volumes:
      # set right value of volume the same value as SOURCE_VOLUME
      - //c/tmp/source:/tmp/c_tmp_source
      # set right value of volume the same value as DESTINATION_VOLUME
      - //c/tmp/destination:/tmp/c_tmp_destination
    environment:
      SOURCE_VOLUME: /tmp/c_tmp_source
      DESTINATION_VOLUME: /tmp/c_tmp_destination
      TZ: Europe/Moscow
    depends_on:
      - mongodb
