version: '3.9'

services:
  mongodb:
    image: mongo
    container_name: my-mongo
    ports:
      - "27000:27017"
    volumes:
      - ./mongo-data:/data/db

  app:
    build: .
    container_name: my-csharp-app
    volumes:
      - //c/tmp/source:/tmp/c_tmp_source
      - //c/tmp/destination:/tmp/c_tmp_destination
    environment:
      SOURCE_VOLUME: /tmp/c_tmp_source
      DESTINATION_VOLUME: /tmp/c_tmp_destination
      TZ: Europe/Moscow
    depends_on:
      - mongodb
